[package]
edition = "2024"
name = "chuck_core"
version = "0.1.0"

[dependencies]
embassy-futures = "0.1.1"
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
esp-hal = { version = "^1.0.0-beta", features = ["defmt", "esp32c3", "unstable"] }

[dev-dependencies]
