[package]
edition = "2024"
name = "chuck_core"
version = "0.1.0"

[dependencies]
embassy-futures = "0.1.1"
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
embedded-hal = "1.0.0"

[dev-dependencies]
